server:
  port: 8087

spring:
  application:
    name: "todolist"

  main:
    banner-mode: off

  profiles:
    active: dev, h2

  jpa:
    hibernate:
      ddl-auto: update

logging:
  file:
    path: logs/

jwt:
  key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B597031415927182820232023

  lifetime:
    access-token: 1800000   # 30 minutes
    refresh-token: 86400000 # a day