spring:
  datasource:
    username: user
    password: pass
    url: jdbc:h2:file:./h2/TODOLIST;AUTO_SERVER=true;
#    url: jdbc:sqlite:identifier.sqlite
#    driver-class-name: org.sqlite.JDBC

#  jpa:
#    database-platform: org.hibernate.community.dialect.SQLiteDialect