server:
  port: 8080

spring:
  application:
    name: "todolist"

  main:
    banner-mode: off

  profiles:
    active: mysql

  jpa:
    hibernate:
      ddl-auto: update

logging:
  file:
    path: /logs
