server:
  port: 8080

spring:
  application:
    name: "todolist"

  main:
    banner-mode: off

  profiles:
    active: debug, h2

  jpa:
    hibernate:
      ddl-auto: update

logging:
  file:
    path: logs/

jwt:
  key: ${JWT_KEY}

  lifetime:
    access-token: 1800000   # 30 minutes
    refresh-token: 86400000 # a day