version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todolist
    ports:
      - '5433:5432'
    expose:
      - '5433'
    volumes:
      - db:/var/lib/postgresql/data


  todolist:
    image: todolist:0.0.1-SNAPSHOT
#    restart: always
    ports:
      - '8087:8087'
    expose:
      - '8087'
    depends_on:
      - db


volumes:
  db:
    driver: local